### ISSUE TITLE
Angular.js is Duplicating Summernote Editors (FIXED)

### ISSUE THREAD

**Issue by hasansahinnn** [ilyasozkurt/summernote-sticky-toolbar#1]
Hello everyone,

When I tried to add this to my project, my editor duplicated with every key press. I solved this problem by doing the following:

![image](https://github.com/ilyasozkurt/summernote-sticky-toolbar/assets/44510615/1e89440a-e4c5-486a-abf5-3ae260696f34)

Thanks for sharing ilyas.

**Comment by ilyasozkurt** [comment]
Hello Hasan,

Thank you for your contribution.
